import { h, Fragment, MapPin, ChevronRight } from './runtime.js';
import { levels, originLabel, relativeTime, maintenanceTime, hasCoordinates, installationCheck } from './bin-model.js';
export const emptyFilters = { q: '', province: '', district: '', risk: 'all', origin: 'all', coordinates: 'all' };
export function TrafficLegend() { return h("div", { className: "map-legend traffic-legend" }, Object.entries(levels).map(([k, v]) => h("span", { key: k },
    h("i", { style: { background: v.color } }),
    v.label))); }
export function CatalogSummary({ meta, loading, error, onRetry }) { return h("div", { className: "catalog-summary" },
    h("div", null,
        h("b", null,
            h(MapPin, { size: 16 }),
            "\uC804\uAD6D \uACF5\uACF5\uB370\uC774\uD130 \uAE30\uBCF8 \uC9C0\uB3C4"),
        h("span", null, meta ? h(Fragment, null,
            "\uC218\uB85D ",
            meta.total.toLocaleString(),
            "\uACF3 \u00B7 \uC88C\uD45C \uC81C\uACF5 ",
            meta.located.toLocaleString(),
            "\uACF3 \u00B7 \uC88C\uD45C \uBBF8\uC81C\uACF5 ",
            meta.missingCoordinates.toLocaleString(),
            "\uACF3") : loading ? '자료를 불러오고 있어요…' : '자료를 불러오지 못했어요.')),
    h("p", null,
        "\uC81C\uBCF4\uAC00 \uC5C6\uC5B4\uB3C4 \uC218\uAC70\uD568\uC740 \uD45C\uC2DC\uB3FC\uC694. \uD68C\uC0C9\uC740 \uC544\uC9C1 \uC0C1\uD0DC \uBBF8\uD655\uC778, \uC0C9\uC0C1\uC740 \uC2DC\uBBFC \uAD00\uCC30\uC5D0 \uB530\uB978 \uCC38\uACE0 \uB2E8\uACC4\uC608\uC694. ",
        h("span", null, "\uC22B\uC790\uB294 \uBB36\uC778 \uC218\uAC70\uD568 \uC218\uC774\uBA70, \uBAA8\uC74C \uC0C9\uC0C1\uC740 \uB0B4\uBD80 \uCD5C\uACE0 \uC8FC\uC758 \uB2E8\uACC4\uC785\uB2C8\uB2E4.")),
    error && h("div", { className: "error-box", role: "alert" },
        error,
        " ",
        h("button", { className: "text-button", onClick: onRetry }, "\uB2E4\uC2DC \uBD88\uB7EC\uC624\uAE30"))); }
export function CatalogControls({ bins, filters, onChange, showCoordinates = false }) { const change = (key, value) => onChange({ ...filters, [key]: value, ...(key === 'province' ? { district: '' } : {}) }); const provinces = [...new Set(bins.map(b => b.province).filter(Boolean))].sort((a, b) => a.localeCompare(b, 'ko')); const districts = [...new Set(bins.filter(b => !filters.province || b.province === filters.province).map(b => b.district).filter(Boolean))].sort((a, b) => a.localeCompare(b, 'ko')); return h("div", { className: "catalog-controls" },
    h("input", { className: "text-input catalog-search", "aria-label": "\uACF5\uACF5 \uC218\uAC70\uD568 \uC8FC\uC18C\u00B7\uC7A5\uC18C \uAC80\uC0C9", placeholder: "\uC218\uAC70\uD568 \uC8FC\uC18C \u00B7 \uB3D9 \uC774\uB984 \u00B7 \uC7A5\uC18C \uAC80\uC0C9", value: filters.q, maxLength: 200, onChange: e => change('q', e.target.value) }),
    h("select", { className: "text-input", "aria-label": "\uC218\uAC70\uD568 \uC2DC\uB3C4", value: filters.province, onChange: e => change('province', e.target.value) },
        h("option", { value: "" }, "\uC804\uAD6D \u00B7 \uBAA8\uB4E0 \uC2DC\uB3C4"),
        provinces.map(p => h("option", { key: p }, p))),
    h("select", { className: "text-input", "aria-label": "\uC218\uAC70\uD568 \uC2DC\uAD70\uAD6C", value: filters.district, onChange: e => change('district', e.target.value) },
        h("option", { value: "" }, "\uBAA8\uB4E0 \uC2DC\uAD70\uAD6C"),
        districts.map(p => h("option", { key: p }, p))),
    h("select", { className: "text-input", "aria-label": "\uC218\uAC70\uD568 \uC704\uD5D8\uB3C4", value: filters.risk, onChange: e => change('risk', e.target.value) },
        h("option", { value: "all" }, "\uBAA8\uB4E0 \uC704\uD5D8\uB3C4"),
        Object.entries(levels).map(([k, v]) => h("option", { value: k, key: k },
            v.emoji,
            " ",
            v.label))),
    h("select", { className: "text-input", "aria-label": "\uC218\uAC70\uD568 \uC790\uB8CC \uAD6C\uBD84", value: filters.origin, onChange: e => change('origin', e.target.value) },
        h("option", { value: "all" }, "\uACF5\uACF5\uC790\uB8CC + \uC2DC\uBBFC \uBC1C\uACAC"),
        h("option", { value: "public" }, "\uACF5\uACF5\uC790\uB8CC \uC218\uB85D"),
        h("option", { value: "citizen" }, "\uACF5\uACF5\uC790\uB8CC \uBBF8\uB9E4\uCE6D \u00B7 \uD589\uC815 \uD655\uC778")),
    showCoordinates && h("select", { className: "text-input", "aria-label": "\uC88C\uD45C \uC81C\uACF5 \uC5EC\uBD80", value: filters.coordinates, onChange: e => change('coordinates', e.target.value) },
        h("option", { value: "all" }, "\uC88C\uD45C \uC81C\uACF5 \uC5EC\uBD80 \uC804\uCCB4"),
        h("option", { value: "provided" }, "\uC9C0\uB3C4 \uD45C\uC2DC \uAC00\uB2A5"),
        h("option", { value: "missing" }, "\uC88C\uD45C \uBBF8\uC81C\uACF5")),
    h("button", { className: "text-button", onClick: () => onChange({ ...emptyFilters }) }, "\uCD08\uAE30\uD654")); }
export function BinCard({ bin: b, onOpen }) { const install = installationCheck(b); return h("button", { className: "report-card bin-record-card", onClick: () => onOpen(b) },
    h("div", { className: "bin-card-head" },
        h("span", { className: `bin-source-tag ${b.origin === 'citizen' ? 'citizen' : ''}` }, b.origin === 'citizen' ? '미등록 후보' : '공공자료'),
        h(ChevronRight, { size: 17 })),
    h("h3", null, b.title),
    h("p", { className: "bin-card-address" }, b.address),
    h("div", { className: `bin-risk-band ${b.level}` },
        h("span", null, levels[b.level].emoji),
        h("b", null, b.score == null ? '점수 없음' : `${b.score}점`),
        h("span", null, levels[b.level].label)),
    h("div", { className: "bin-card-counts" },
        h("span", null,
            "\uCD5C\uADFC 30\uC77C \uC81C\uBCF4 ",
            h("b", null,
                b.recentCount,
                "\uAC74")),
        h("span", null, b.lastMaintenance ? `마지막 정비 ${relativeTime(maintenanceTime(b.lastMaintenance))}` : '정비 이력 없음')),
    h("div", { className: "card-bottom" },
        h("span", null, b.origin === 'citizen' ? install.label : `자료 기준 ${b.checked || '확인 필요'}`),
        !hasCoordinates(b) && h("span", { className: "coordinate-missing" }, "\uC88C\uD45C \uBBF8\uC81C\uACF5"))); }
